internlm-7b-hf:
    ARC-c: 34.24
    chid-dev: 79.70
    chid-test: 81.12
    openai_humaneval: 10.98
    openbookqa: 47.20
    openbookqa_fact: 74.00

internlm-chat-7b-hf:
    ARC-c: 36.95
    chid-dev: 71.78
    chid-test: 76.87
    openai_humaneval: 21.34
    openbookqa: 66.6
    openbookqa_fact: 80.4

chatglm3-6b-base-hf:
    ARC-c: 44.41
    chid-dev: 78.22
    chid-test: 78.57
    openai_humaneval: 20.73
    openbookqa: 78.40
    openbookqa_fact: 92.00

internlm2-7b-hf:
    ARC-c: 36.27
    chid-dev: 55.94
    chid-test: 53.70
    openai_humaneval: 45.12
    openbookqa: 80.00
    openbookqa_fact: 86.40
