chat:
    qwen3_0_6b_fp8-hf:
        gsm8k_accuracy: 3.12
        race-high_accuracy: 6.25
    qwen3-0_6b-fp8-turbomind:
        gsm8k_accuracy: 40.62
        race-high_accuracy: 65.62
base:
    qwen3-8b-base-turbomind:
        gsm8k_accuracy: 50.00
        GPQA_diamond_accuracy: 15.62
        race-high_accuracy: 62.50
        winogrande_accuracy: 71.88
    qwen3-8b-base-vllm:
        gsm8k_accuracy: 53.12
        GPQA_diamond_accuracy: 18.75
        race-high_accuracy: 59.38
        winogrande_accuracy: 71.88
    qwen3-8b-base-hf:
        gsm8k_accuracy: 50.00
        GPQA_diamond_accuracy: 18.75
        race-high_accuracy: 59.38
        winogrande_accuracy: 53.12
