assign:
  issues: enabled
  pull_requests: disabled
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
    - bittersweet1999
    - liushz
    - MaiziXiao
    - acylam
    - tonysy
