assign:
  issues: enabled
  pull_requests: disabled
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
    - Leymore
    - bittersweet1999
    - yingfhu
    - kennymckormick
    - tonysy
