supergpqa_summary_groups = []

# gaokao-bench
supergpqa_weights = {
'Electronic_Science_and_Technology': 246,
'Philosophy': 347,
'Traditional_Chinese_Medicine': 268,
'Applied_Economics': 723,
'Mathematics': 2622,
'Physics': 2845,
'Clinical_Medicine': 1218,
'Computer_Science_and_Technology': 763,
'Information_and_Communication_Engineering': 504,
'Control_Science_and_Engineering': 190,
'Theoretical_Economics': 150,
'Law': 591,
'History': 674,
'Basic_Medicine': 567,
'Education': 247,
'Materials_Science_and_Engineering': 289,
'Electrical_Engineering': 556,
'Systems_Science': 50,
'Power_Engineering_and_Engineering_Thermophysics': 684,
'Military_Science': 205,
'Biology': 1120,
'Business_Administration': 142,
'Language_and_Literature': 440,
'Public_Health_and_Preventive_Medicine': 292,
'Political_Science': 65,
'Chemistry': 1769,
'Hydraulic_Engineering': 218,
'Chemical_Engineering_and_Technology': 410,
'Pharmacy': 278,
'Geography': 133,
'Art_Studies': 603,
'Architecture': 162,
'Forestry_Engineering': 100,
'Public_Administration': 151,
'Oceanography': 200,
'Journalism_and_Communication': 207,
'Nuclear_Science_and_Technology': 107,
'Weapon_Science_and_Technology': 100,
'Naval_Architecture_and_Ocean_Engineering': 138,
'Environmental_Science_and_Engineering': 189,
'Transportation_Engineering': 251,
'Geology': 341,
'Physical_Oceanography': 50,
'Musicology': 426,
'Stomatology': 132,
'Aquaculture': 56,
'Mechanical_Engineering': 176,
'Aeronautical_and_Astronautical_Science_and_Technology': 119,
'Civil_Engineering': 358,
'Mechanics': 908,
'Petroleum_and_Natural_Gas_Engineering': 112,
'Sociology': 143,
'Food_Science_and_Engineering': 109,
'Agricultural_Engineering': 104,
'Surveying_and_Mapping_Science_and_Technology': 168,
'Metallurgical_Engineering': 255,
'Library,_Information_and_Archival_Management': 150,
'Mining_Engineering': 100,
'Astronomy': 405,
'Geological_Resources_and_Geological_Engineering': 50,
'Atmospheric_Science': 203,
'Optical_Engineering': 376,
'Animal_Husbandry': 103,
'Geophysics': 100,
'Crop_Science': 145,
'Management_Science_and_Engineering': 58,
'Psychology': 87,
'Forestry': 131,
'Textile_Science_and_Engineering': 100,
'Veterinary_Medicine': 50,
'Instrument_Science_and_Technology': 50,
'Physical_Education': 150,
}
supergpqa_weights = {
    'supergpqa_' + k: v for k, v in supergpqa_weights.items()
}
supergpqa_summary_groups.append(
    {
        'name': 'SuperGPQA',
        'subsets':[[k, 'accuracy'] for k in supergpqa_weights.keys()],
        'weights': supergpqa_weights,
    }
)

print(supergpqa_summary_groups)